<a href="https://colab.research.google.com/github/AeroEngineerUTK/Astronautics-SpaceFlight_Mikhail-LaMay/blob/main/AtmosphericAndSpaceFlightDynamics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Subject: Atmospheric & SpaceFlight Dynamics

In [ ]:
# ---- Example 2.1 ---- #
# - Let us find scalar and vector products of A_mag = -2i + 5j - k and
#     B_mag = i + 3k.

def Example_2_1():

# Variables [Vectors]
    A = [-2,5,-1] # Vector A
    B = [1,0,3] # Vector B

# Dot Product (s = dot(A,B))
    s = A[0]*B[0] + A[1]*B[1] + A[2]*B[2]

# Cross Product (C = cross(A,B))
    Ci = A[1]*B[2] - A[2]*B[1]
    Cj = A[2]*B[0] - A[0]*B[2]
    Ck = A[0]*B[1] - A[1]*B[0]
    C = [Ci,Cj,Ck]

# Cross Product (D=cross(B,A))
    Di = B[1]*A[2] - B[2]*A[1]
    Dj = B[2]*A[0] - B[0]*A[2]
    Dk = B[0]*A[1] - B[1]*A[0]
    D = [Di,Dj,Dk]

# Triple Cross Product (E = cross(A,cross(A,B)) = cross(A,C))
    Ei = A[1]*C[2] - A[2]*C[1]
    Ej = A[2]*C[0] - A[0]*C[2]
    Ek = A[0]*C[1] - A[1]*C[0]
    E = [Ei,Ej,Ek]

# Print Results
    # print(s,'\n',C,'\n',D,'\n',E)

def main():
    Example_2_1()

if __name__ == '__main__':
    main()

In [ ]:
# ---- Example 2.2 ---- #
# - Find the rotation matrix that produces the right-hand coordinate frame
#   i',j',k' given by i' = 0.1i + 0.2j + (sqrt(1 - 0.01 - 0.04))k, and
#   j'= -0.1i - 0.9726095077j + (sqrt(1 - 0.01 - 0.9726095077^2))k

# Libraries Required:
import numpy as np

def Example_2_2():

# Variables: [Vectors]
  iprime = [0.1,0.2,np.sqrt(1 - 0.01 - 0.04)]
  jprime = [-0.1,-0.9726095077,np.sqrt(1 - 0.01 - 0.9726095077**2)]
  # print(iprime,'\n',jprime,'\n')

# Take Dot Product: [dot(iprime,jprime)]
  dot_iprime_jprime = np.dot(iprime,jprime)
  # print(dot_iprime_jprime,'\n')

# Take Cross Product: [cross(iprime,jprime)] [k' = i',j']
  kprime = np.cross(iprime,jprime)
  # print(kprime)

# Define New Variables:
  i = np.array([[1],[0],[0]])
  j = np.array([[0],[1],[0]])
  k = np.array([[0],[0],[1]])
  # print(i,'\n',j,'\n',k,'\n')

# Create The Direction Cosine Matrix, Or The Rotation Matrix
  C = np.array([
                [np.dot(iprime,i),np.dot(jprime,i),np.dot(kprime,i)],
                [np.dot(iprime,j),np.dot(jprime,j),np.dot(kprime,j)],
                [np.dot(iprime,k),np.dot(jprime,k),np.dot(kprime,k)]
                ])

  C_trans = C.T # Transpose Rotation Matrix
  print(C_trans)

# Take Determinant: [The Rotation Matrix]
  # det = np.linalg.det(C)
  # print(int(det))

def main():
    Example_2_2()

if __name__ == '__main__':
    main()

[[[ 0.1         0.2         0.97467943]
  [-0.1        -0.97260951  0.20983504]
  [ 0.98994949 -0.11845145 -0.07726095]]]
